name: Example Test Run
run-name: Testing a single test
on:
  push:
    branches:
      - main
jobs:
  Run-A-Single-UI-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Setup Chrome Browser and ChromeDriver
        run: |
          sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
          sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get -y update
          sudo apt-get -y install google-chrome-stable
          wget https://chromedriver.storage.googleapis.com/$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chown root:root /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Run A Single Tests
        run: mvn test

#      - name: Upload Test Results
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: Smoke Test Results HTML File
#          path: target/cucumber-report/report.html







